#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyStash.Droid.Resource", IsApplication=true)]

namespace MyStash.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLStorage.Resource.String.ApplicationName = global::MyStash.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::MyStash.Droid.Resource.String.Hello;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MyStash.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MyStash.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::MyStash.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int edit = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EditPassword = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int error = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int info = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Lock = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Login = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int misc = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Note = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int success = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int toolbarcheckpw = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int toolbartimer = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ViewAll = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int warning = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int desc = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int description = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int image = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int title = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int crouton = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int crouton_error = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
