using System;
using MyStash.ResX;

namespace MyStash.Export
{
    public static class Consts
    {
        /// <summary>
        /// CR LF constant
        /// </summary>
        public static string NewLine = Environment.NewLine;

        /// <summary>
        /// Current library version. Must _not_ be changed !
        /// </summary>
        public static string AppVersion = "PCL1.1";

        /// <summary>
        /// "Generated by" message including E-Naxos copyrights. Must _not_ be changed !
        /// </summary>
        public static string GeneratedBy = AppResources.Consts_GeneratedBy_Generated_By_MyStash;


        /// <summary>
        /// "Out of range percentage" message. Can be localized.
        /// </summary>
        public static string BadPercent = AppResources.Consts_BadPercent_Bad_percentage;

        /// <summary>
        /// "Empty file name" message. Can be localized.
        /// </summary>
        public static string EmptyFileName = AppResources.Consts_EmptyFileName_File_name_is_empty;

        /// <summary>
        /// "File already exists" message. Can be localized.
        /// Localized version must include the marker {0} that represents the file name.
        /// </summary>
        public static string FileExists = AppResources.Consts_FileExists_Destination_file_already_exists;

        /// <summary>
        /// "Empty source" message. Can be localized.
        /// </summary>
        public static string SourceEmpty = AppResources.Consts_SourceEmpty_No_data_in_source_to_process;

        /// <summary>
        /// "Null source" message. Can be localized.
        /// </summary>
        public static string SourceIsNull = AppResources.Consts_SourceIsNull_Source_is_null;
    }
}