//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStash.ResX {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyStash.ResX.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyStash.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string AppSettings_CultureDictionary_Default {
            get {
                return ResourceManager.GetString("AppSettings_CultureDictionary_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string AppSettings_CultureDictionary_English {
            get {
                return ResourceManager.GetString("AppSettings_CultureDictionary_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string AppSettings_CultureDictionary_French {
            get {
                return ResourceManager.GetString("AppSettings_CultureDictionary_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string AppSettings_CultureDictionary_German {
            get {
                return ResourceManager.GetString("AppSettings_CultureDictionary_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string AppSettings_CultureDictionary_Italian {
            get {
                return ResourceManager.GetString("AppSettings_CultureDictionary_Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string AppSettings_CultureDictionary_Russian {
            get {
                return ResourceManager.GetString("AppSettings_CultureDictionary_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad percentage.
        /// </summary>
        internal static string Consts_BadPercent_Bad_percentage {
            get {
                return ResourceManager.GetString("Consts_BadPercent_Bad_percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is empty.
        /// </summary>
        internal static string Consts_EmptyFileName_File_name_is_empty {
            get {
                return ResourceManager.GetString("Consts_EmptyFileName_File_name_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination file already exists.
        /// </summary>
        internal static string Consts_FileExists_Destination_file_already_exists {
            get {
                return ResourceManager.GetString("Consts_FileExists_Destination_file_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated By MyStash.
        /// </summary>
        internal static string Consts_GeneratedBy_Generated_By_MyStash {
            get {
                return ResourceManager.GetString("Consts_GeneratedBy_Generated_By_MyStash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data in source to process.
        /// </summary>
        internal static string Consts_SourceEmpty_No_data_in_source_to_process {
            get {
                return ResourceManager.GetString("Consts_SourceEmpty_No_data_in_source_to_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source is null.
        /// </summary>
        internal static string Consts_SourceIsNull_Source_is_null {
            get {
                return ResourceManager.GetString("Consts_SourceIsNull_Source_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_Edit {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_Invalid_URL {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_Invalid_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login copied to clipboard.
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_Login_copied_to_clipboard {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_Login_copied_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More time.
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_More_time {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_More_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note copied to clipboard.
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_Note_copied_to_clipboard {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_Note_copied_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password copied to clipboard.
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_Password_copied_to_clipboard {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_Password_copied_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perhaps are you missing the protocol name (&apos;http://&apos; for example) ?.
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_Perhaps_are_you_missing_the_protocol_name___http_____for_example___ {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_Perhaps_are_you_missing_the_protocol_name___http_" +
                        "____for_example___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login has been copied to the clipboard.
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_The_login_has_been_copied_to_the_clipboard {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_The_login_has_been_copied_to_the_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The note has been copied to the clipboard.
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_The_note_has_been_copied_to_the_clipboard {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_The_note_has_been_copied_to_the_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been copied to the clipboard.
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_The_password_has_been_copied_to_the_clipboard {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_The_password_has_been_copied_to_the_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve got {0} seconds more..
        /// </summary>
        internal static string DetailViewModel_DetailViewModel_You_ve_got__0__seconds_more_ {
            get {
                return ResourceManager.GetString("DetailViewModel_DetailViewModel_You_ve_got__0__seconds_more_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogService_ShowMessage_Cancel {
            get {
                return ResourceManager.GetString("DialogService_ShowMessage_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string DialogService_ShowMessage_Ok {
            get {
                return ResourceManager.GetString("DialogService_ShowMessage_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string EditView_Title {
            get {
                return ResourceManager.GetString("EditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action canceled.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Action_canceled {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Action_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete data.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Can_t_delete_data {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Can_t_delete_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save data.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Can_t_save_data {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Can_t_save_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Confirmation {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data deleted.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Data_deleted {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Data_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data error.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Data_error {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Data_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been deleted.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Data_has_been_deleted {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Data_has_been_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been saved.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Data_has_been_saved {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Data_has_been_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data have NOT been deleted..
        /// </summary>
        internal static string EditViewModel_EditViewModel_Data_have_NOT_been_deleted_ {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Data_have_NOT_been_deleted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data have not been modified.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Data_have_not_been_modified {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Data_have_not_been_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data have NOT been saved..
        /// </summary>
        internal static string EditViewModel_EditViewModel_Data_have_NOT_been_saved_ {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Data_have_NOT_been_saved_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Data_saved {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Data_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data. Are you sure ?.
        /// </summary>
        internal static string EditViewModel_EditViewModel_Delete_data__Are_you_sure__ {
            get {
                return ResourceManager.GetString("EditViewModel_EditViewModel_Delete_data__Are_you_sure__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category must be selected.
        /// </summary>
        internal static string EditViewModel_isSheetOkVerbose_A_category_must_be_selected {
            get {
                return ResourceManager.GetString("EditViewModel_isSheetOkVerbose_A_category_must_be_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Login name.
        /// </summary>
        internal static string EditViewModel_isSheetOkVerbose_Enter_a_Login_name {
            get {
                return ResourceManager.GetString("EditViewModel_isSheetOkVerbose_Enter_a_Login_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password.
        /// </summary>
        internal static string EditViewModel_isSheetOkVerbose_Enter_a_password {
            get {
                return ResourceManager.GetString("EditViewModel_isSheetOkVerbose_Enter_a_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a title.
        /// </summary>
        internal static string EditViewModel_isSheetOkVerbose_Enter_a_title {
            get {
                return ResourceManager.GetString("EditViewModel_isSheetOkVerbose_Enter_a_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter something in Note field.
        /// </summary>
        internal static string EditViewModel_isSheetOkVerbose_Enter_something_in_Note_field {
            get {
                return ResourceManager.GetString("EditViewModel_isSheetOkVerbose_Enter_something_in_Note_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is empty.
        /// </summary>
        internal static string EditViewModel_isSheetOkVerbose_Login_is_empty {
            get {
                return ResourceManager.GetString("EditViewModel_isSheetOkVerbose_Login_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note is empty.
        /// </summary>
        internal static string EditViewModel_isSheetOkVerbose_Note_is_empty {
            get {
                return ResourceManager.GetString("EditViewModel_isSheetOkVerbose_Note_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty.
        /// </summary>
        internal static string EditViewModel_isSheetOkVerbose_Password_is_empty {
            get {
                return ResourceManager.GetString("EditViewModel_isSheetOkVerbose_Password_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        internal static string EditViewModel_isSheetOkVerbose_Select_a_category {
            get {
                return ResourceManager.GetString("EditViewModel_isSheetOkVerbose_Select_a_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is mandatory.
        /// </summary>
        internal static string EditViewModel_isSheetOkVerbose_Title_is_mandatory {
            get {
                return ResourceManager.GetString("EditViewModel_isSheetOkVerbose_Title_is_mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventToCommandBehavior: Can&apos;t de-register the &apos;{0}&apos; event..
        /// </summary>
        internal static string EventToCommandBehavior_CantDeRegisterEvent {
            get {
                return ResourceManager.GetString("EventToCommandBehavior_CantDeRegisterEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventToCommandBehavior: Can&apos;t register the &apos;{0}&apos; event..
        /// </summary>
        internal static string EventToCommandBehavior_CantRegisterEvent {
            get {
                return ResourceManager.GetString("EventToCommandBehavior_CantRegisterEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read property {0}.
        /// </summary>
        internal static string ExportBase_GetFieldValue_Can_t_read_property__0_ {
            get {
                return ResourceManager.GetString("ExportBase_GetFieldValue_Can_t_read_property__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyStash CSV data.
        /// </summary>
        internal static string ExportClipboardCsv_CloseOutput_MyStash_CSV_data {
            get {
                return ResourceManager.GetString("ExportClipboardCsv_CloseOutput_MyStash_CSV_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no shell execute in PCL version.
        /// </summary>
        internal static string ExportClipboardCsv_ExecuteOutput_no_shell_execute_in_PCL_version {
            get {
                return ResourceManager.GetString("ExportClipboardCsv_ExecuteOutput_no_shell_execute_in_PCL_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyStash SQL data.
        /// </summary>
        internal static string ExportClipboardSql_CloseOutput_MyStash_SQL_data {
            get {
                return ResourceManager.GetString("ExportClipboardSql_CloseOutput_MyStash_SQL_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no shell execute in PCL version.
        /// </summary>
        internal static string ExportClipboardSql_ExecuteOutput_no_shell_execute_in_PCL_version {
            get {
                return ResourceManager.GetString("ExportClipboardSql_ExecuteOutput_no_shell_execute_in_PCL_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click to generate!.
        /// </summary>
        internal static string GeneratePwViewModel_generated_click_to_generate_ {
            get {
                return ResourceManager.GetString("GeneratePwViewModel_generated_click_to_generate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string GeneratePwViewModel_GeneratePwViewModel_Copy_to_clipboard {
            get {
                return ResourceManager.GetString("GeneratePwViewModel_GeneratePwViewModel_Copy_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated password copied to the clipboard.
        /// </summary>
        internal static string GeneratePwViewModel_GeneratePwViewModel_Generated_password_copied_to_the_clipboard {
            get {
                return ResourceManager.GetString("GeneratePwViewModel_GeneratePwViewModel_Generated_password_copied_to_the_clipboar" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Stash generated password.
        /// </summary>
        internal static string GeneratePwViewModel_IncomingCommand_My_Stash_generated_password {
            get {
                return ResourceManager.GetString("GeneratePwViewModel_IncomingCommand_My_Stash_generated_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Data Imported.
        /// </summary>
        internal static string ImportViewModel_Mode__0__Data_Import {
            get {
                return ResourceManager.GetString("ImportViewModel_Mode__0__Data_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string InfoSheet_CategoryDictionary_Login {
            get {
                return ResourceManager.GetString("InfoSheet_CategoryDictionary_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string InfoSheet_CategoryDictionary_Misc {
            get {
                return ResourceManager.GetString("InfoSheet_CategoryDictionary_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string InfoSheet_CategoryDictionary_Note {
            get {
                return ResourceManager.GetString("InfoSheet_CategoryDictionary_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string InfoSheet_ProFilterDictionary_All {
            get {
                return ResourceManager.GetString("InfoSheet_ProFilterDictionary_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string InfoSheet_ProFilterDictionary_Personal {
            get {
                return ResourceManager.GetString("InfoSheet_ProFilterDictionary_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        internal static string InfoSheet_ProFilterDictionary_Professional {
            get {
                return ResourceManager.GetString("InfoSheet_ProFilterDictionary_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alien.
        /// </summary>
        internal static string LeetMaker_LeetStrengthStr_Alien {
            get {
                return ResourceManager.GetString("LeetMaker_LeetStrengthStr_Alien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner.
        /// </summary>
        internal static string LeetMaker_LeetStrengthStr_Beginner {
            get {
                return ResourceManager.GetString("LeetMaker_LeetStrengthStr_Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connoisseur.
        /// </summary>
        internal static string LeetMaker_LeetStrengthStr_Connoisseur {
            get {
                return ResourceManager.GetString("LeetMaker_LeetStrengthStr_Connoisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elitist.
        /// </summary>
        internal static string LeetMaker_LeetStrengthStr_Elitist {
            get {
                return ResourceManager.GetString("LeetMaker_LeetStrengthStr_Elitist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert.
        /// </summary>
        internal static string LeetMaker_LeetStrengthStr_Expert {
            get {
                return ResourceManager.GetString("LeetMaker_LeetStrengthStr_Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string LeetMaker_LeetStrengthStr_Master {
            get {
                return ResourceManager.GetString("LeetMaker_LeetStrengthStr_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string LeetMaker_LeetStrengthStr_None {
            get {
                return ResourceManager.GetString("LeetMaker_LeetStrengthStr_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novice.
        /// </summary>
        internal static string LeetMaker_LeetStrengthStr_Novice {
            get {
                return ResourceManager.GetString("LeetMaker_LeetStrengthStr_Novice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Path.
        /// </summary>
        internal static string MainViewModel_checkLog_Database_Path {
            get {
                return ResourceManager.GetString("MainViewModel_checkLog_Database_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun constructeur approprié trouvé pour {0}.
        /// </summary>
        internal static string NavigationService_getPage_Aucun_constructeur_approprié_trouvé {
            get {
                return ResourceManager.GetString("NavigationService_getPage_Aucun_constructeur_approprié_trouvé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page inconnue: {0}. NavigationService.Configure a-t-il été oublié ?.
        /// </summary>
        internal static string NavigationService_getPage_Page_inconnue {
            get {
                return ResourceManager.GetString("NavigationService_getPage_Page_inconnue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page inconnue: {0}. NavigationService.Configure a-t-il été oublié ?.
        /// </summary>
        internal static string NavigationService_getPage_Page_inconnueConfigure {
            get {
                return ResourceManager.GetString("NavigationService_getPage_Page_inconnueConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 or more requirements.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails__3_or_more_requirments {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails__3_or_more_requirments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive Lowercase Letters.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Consecutive_Lowercase_Letters {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Consecutive_Lowercase_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive Numbers.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Consecutive_Numbers {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Consecutive_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutive Uppercase Letters.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Consecutive_Uppercase_Letters {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Consecutive_Uppercase_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Empty {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Good {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than 3 requirements.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Less_than_3_requirments {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Less_than_3_requirments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters only.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Letters_only {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Letters_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase Letters.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Lowercase_Letters {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Lowercase_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Numbers or Symbols.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Middle_Numbers_or_Symbols {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Middle_Numbers_or_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Numbers {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers only.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Numbers_only {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Numbers_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Length.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Password_Length {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Password_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Rejected {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated Characters (Case Insensitive).
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Repeat_Characters__Case_Insensitive_ {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Repeat_Characters__Case_Insensitive_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement. Digit.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Requirement__Digit {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Requirement__Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement. Length&gt;8.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Requirement__Length_8 {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Requirement__Length_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement. Lowercase.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Requirement__Lowercase {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Requirement__Lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement. Symbol.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Requirement__Symbol {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Requirement__Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement. Uppercase.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Requirement__Uppercase {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Requirement__Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same symbol.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Same_symbol {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Same_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential Letters (3+).
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Sequential_Letters__3__ {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Sequential_Letters__3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential Numbers (3+).
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Sequential_Numbers__3__ {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Sequential_Numbers__3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Strong {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Symbols {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra Strong.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Ultra_Strong {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Ultra_Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase Letters.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Uppercase_Letters {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Uppercase_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Strong.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Very_Strong {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Very_Strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Weak.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Very_Weak {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Very_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        internal static string PasswordChecker_CheckPasswordWithDetails_Weak {
            get {
                return ResourceManager.GetString("PasswordChecker_CheckPasswordWithDetails_Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string PasswordChecker_createMemoryTable_Score {
            get {
                return ResourceManager.GetString("PasswordChecker_createMemoryTable_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string PasswordChecker_PasswordStrength_Unknown {
            get {
                return ResourceManager.GetString("PasswordChecker_PasswordStrength_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length must be &gt;= 4.
        /// </summary>
        internal static string SetPwViewModel_checkValidity_ {
            get {
                return ResourceManager.GetString("SetPwViewModel_checkValidity_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length must be &lt;= 20 characters.
        /// </summary>
        internal static string SetPwViewModel_checkValidity_20 {
            get {
                return ResourceManager.GetString("SetPwViewModel_checkValidity_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character(s) in password..
        /// </summary>
        internal static string SetPwViewModel_checkValidity_Invalid_character_s__in_password_ {
            get {
                return ResourceManager.GetString("SetPwViewModel_checkValidity_Invalid_character_s__in_password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one single character is used.
        /// </summary>
        internal static string SetPwViewModel_checkValidity_Only_one_single_character_is_used {
            get {
                return ResourceManager.GetString("SetPwViewModel_checkValidity_Only_one_single_character_is_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and control don&apos;t match !.
        /// </summary>
        internal static string SetPwViewModel_checkValidity_Password_and_control_don_t_match__ {
            get {
                return ResourceManager.GetString("SetPwViewModel_checkValidity_Password_and_control_don_t_match__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be empty..
        /// </summary>
        internal static string SetPwViewModel_checkValidity_Password_can_t_be_empty_ {
            get {
                return ResourceManager.GetString("SetPwViewModel_checkValidity_Password_can_t_be_empty_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string SetPwViewModel_SetPwViewModel_Confirmation {
            get {
                return ResourceManager.GetString("SetPwViewModel_SetPwViewModel_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password &apos;{0}&apos; has been recorded. Don&apos;t forget it !.
        /// </summary>
        internal static string SetPwViewModel_SetPwViewModel_Your_new_password___0___has_been_recorded__Don_t_forget_it__ {
            get {
                return ResourceManager.GetString("SetPwViewModel_SetPwViewModel_Your_new_password___0___has_been_recorded__Don_t_fo" +
                        "rget_it__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data will be deleted before import. If not sure switch this option OFF !.
        /// </summary>
        internal static string SettingsViewModel_ClearDbBeforeImport {
            get {
                return ResourceManager.GetString("SettingsViewModel_ClearDbBeforeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid algorithm data could be unreadable.
        /// </summary>
        internal static string SettingsViewModel_csvImport___0___is_not_a_valid_algorithm_data_could_be_unreadable {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport___0___is_not_a_valid_algorithm_data_could_be_unreadab" +
                        "le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid boolean.
        /// </summary>
        internal static string SettingsViewModel_csvImport___0___is_not_a_valid_boolean {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport___0___is_not_a_valid_boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid Category.
        /// </summary>
        internal static string SettingsViewModel_csvImport___0___is_not_a_valid_Category {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport___0___is_not_a_valid_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid date/time.
        /// </summary>
        internal static string SettingsViewModel_csvImport___0___is_not_a_valid_date_time {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport___0___is_not_a_valid_date_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid field position..
        /// </summary>
        internal static string SettingsViewModel_csvImport___0___is_not_a_valid_field_position_ {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport___0___is_not_a_valid_field_position_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid ID.
        /// </summary>
        internal static string SettingsViewModel_csvImport___0___is_not_a_valid_ID {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport___0___is_not_a_valid_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sheets imported. {1} ID skipped. {2} Title skipped..
        /// </summary>
        internal static string SettingsViewModel_csvImport__0__sheets_imported___1__ID_skipped___2__Title_skipped_ {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport__0__sheets_imported___1__ID_skipped___2__Title_skippe" +
                        "d_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupted data (1st line missing).
        /// </summary>
        internal static string SettingsViewModel_csvImport_Corrupted_data__1st_line_missing_ {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport_Corrupted_data__1st_line_missing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field {0} can&apos;t be found.
        /// </summary>
        internal static string SettingsViewModel_csvImport_field__0__can_t_be_found {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport_field__0__can_t_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored data.
        /// </summary>
        internal static string SettingsViewModel_csvImport_Ignored_data {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport_Ignored_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import aborted bad data line {0}.
        /// </summary>
        internal static string SettingsViewModel_csvImport_Import_aborted_bad_data_line__0_ {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport_Import_aborted_bad_data_line__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed.
        /// </summary>
        internal static string SettingsViewModel_csvImport_Import_failed {
            get {
                return ResourceManager.GetString("SettingsViewModel_csvImport_Import_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unencrypted data export is not safe ! Use this mode only for good reasons..
        /// </summary>
        internal static string SettingsViewModel_EncryptedData_Uncrypted_data_export_is_not_safe {
            get {
                return ResourceManager.GetString("SettingsViewModel_EncryptedData_Uncrypted_data_export_is_not_safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string SettingsViewModel_EncryptedData_Warning {
            get {
                return ResourceManager.GetString("SettingsViewModel_EncryptedData_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data are in the clipboard !.
        /// </summary>
        internal static string SettingsViewModel_exportData_Data_are_in_the_clipboard {
            get {
                return ResourceManager.GetString("SettingsViewModel_exportData_Data_are_in_the_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SettingsViewModel_exportData_Error {
            get {
                return ResourceManager.GetString("SettingsViewModel_exportData_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string SettingsViewModel_exportData_Export {
            get {
                return ResourceManager.GetString("SettingsViewModel_exportData_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string SettingsViewModel_exportData_No_data {
            get {
                return ResourceManager.GetString("SettingsViewModel_exportData_No_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to export.
        /// </summary>
        internal static string SettingsViewModel_exportData_No_data_to_export {
            get {
                return ResourceManager.GetString("SettingsViewModel_exportData_No_data_to_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SettingsViewModel_exportData_OK {
            get {
                return ResourceManager.GetString("SettingsViewModel_exportData_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sheets have been imported..
        /// </summary>
        internal static string SettingsViewModel_importCSVWithData__0__sheets_have_been_imported_ {
            get {
                return ResourceManager.GetString("SettingsViewModel_importCSVWithData__0__sheets_have_been_imported_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import succeeded.
        /// </summary>
        internal static string SettingsViewModel_importCSVWithData_Import_succeed {
            get {
                return ResourceManager.GetString("SettingsViewModel_importCSVWithData_Import_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data have been imported..
        /// </summary>
        internal static string SettingsViewModel_importCSVWithData_No_data_have_been_imported_ {
            get {
                return ResourceManager.GetString("SettingsViewModel_importCSVWithData_No_data_have_been_imported_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data imported.
        /// </summary>
        internal static string SettingsViewModel_importCSVWithData_No_data_imported {
            get {
                return ResourceManager.GetString("SettingsViewModel_importCSVWithData_No_data_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SQL import in this version.
        /// </summary>
        internal static string SettingsViewModel_importSql_No_SQL_import_in_this_version {
            get {
                return ResourceManager.GetString("SettingsViewModel_importSql_No_SQL_import_in_this_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented.
        /// </summary>
        internal static string SettingsViewModel_importSql_Not_implemented {
            get {
                return ResourceManager.GetString("SettingsViewModel_importSql_Not_implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comp is not a member of StringComparison.
        /// </summary>
        internal static string StringExtensions_Contains_comp_is_not_a_member_of_StringComparison {
            get {
                return ResourceManager.GetString("StringExtensions_Contains_comp_is_not_a_member_of_StringComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substring cannot be null..
        /// </summary>
        internal static string StringExtensions_Contains_substring_cannot_be_null_ {
            get {
                return ResourceManager.GetString("StringExtensions_Contains_substring_cannot_be_null_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not forget your password ! There is no backdoor and we DO NOT have any magical trick to help you....
        /// </summary>
        internal static string VewSetPW_Warning {
            get {
                return ResourceManager.GetString("VewSetPW_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string ViewCheckPw_Bonus {
            get {
                return ResourceManager.GetString("ViewCheckPw_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malus.
        /// </summary>
        internal static string ViewCheckPw_Malus {
            get {
                return ResourceManager.GetString("ViewCheckPw_Malus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string ViewCheckPw_Strength {
            get {
                return ResourceManager.GetString("ViewCheckPw_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Analysis.
        /// </summary>
        internal static string ViewCheckPw_Title {
            get {
                return ResourceManager.GetString("ViewCheckPw_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check PW.
        /// </summary>
        internal static string ViewDetail_CheckPw {
            get {
                return ResourceManager.GetString("ViewDetail_CheckPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name/Url.
        /// </summary>
        internal static string ViewDetail_NameOrURL {
            get {
                return ResourceManager.GetString("ViewDetail_NameOrURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ViewDetail_Password {
            get {
                return ResourceManager.GetString("ViewDetail_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string ViewDetail_Title {
            get {
                return ResourceManager.GetString("ViewDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ViewEdit_DeleteButton {
            get {
                return ResourceManager.GetString("ViewEdit_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string ViewEdit_NoteSection {
            get {
                return ResourceManager.GetString("ViewEdit_NoteSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data.
        /// </summary>
        internal static string ViewEdit_TitleCreate {
            get {
                return ResourceManager.GetString("ViewEdit_TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify data.
        /// </summary>
        internal static string ViewEdit_TitleModify {
            get {
                return ResourceManager.GetString("ViewEdit_TitleModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ViewGeneratePW_BackButton {
            get {
                return ResourceManager.GetString("ViewGeneratePW_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string ViewGeneratePW_Generate {
            get {
                return ResourceManager.GetString("ViewGeneratePW_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obfuscation level.
        /// </summary>
        internal static string ViewGeneratePW_LeetLevel {
            get {
                return ResourceManager.GetString("ViewGeneratePW_LeetLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L33t Mode (else Random mode).
        /// </summary>
        internal static string ViewGeneratePW_LeetModeSwitch {
            get {
                return ResourceManager.GetString("ViewGeneratePW_LeetModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string ViewGeneratePW_Length {
            get {
                return ResourceManager.GetString("ViewGeneratePW_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password to encode.
        /// </summary>
        internal static string ViewGeneratePW_OriginalWord {
            get {
                return ResourceManager.GetString("ViewGeneratePW_OriginalWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string ViewGeneratePW_Parameters {
            get {
                return ResourceManager.GetString("ViewGeneratePW_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        internal static string ViewGeneratePW_Symbols {
            get {
                return ResourceManager.GetString("ViewGeneratePW_Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generation.
        /// </summary>
        internal static string ViewGeneratePW_Title {
            get {
                return ResourceManager.GetString("ViewGeneratePW_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste here the FULL text of a preceding My Stash export. Then click Ok to proceed.
        /// </summary>
        internal static string ViewImport_Explanation {
            get {
                return ResourceManager.GetString("ViewImport_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your code.
        /// </summary>
        internal static string ViewMain_Title {
            get {
                return ResourceManager.GetString("ViewMain_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ViewMainList_AllPlural {
            get {
                return ResourceManager.GetString("ViewMainList_AllPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PW.
        /// </summary>
        internal static string ViewMainList_ChangePassword {
            get {
                return ResourceManager.GetString("ViewMainList_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Data....
        /// </summary>
        internal static string ViewMainList_LoadingData {
            get {
                return ResourceManager.GetString("ViewMainList_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Screen.
        /// </summary>
        internal static string ViewMainList_LockScreen {
            get {
                return ResourceManager.GetString("ViewMainList_LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins.
        /// </summary>
        internal static string ViewMainList_Logins {
            get {
                return ResourceManager.GetString("ViewMainList_Logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string ViewMainList_MiscPlural {
            get {
                return ResourceManager.GetString("ViewMainList_MiscPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry.
        /// </summary>
        internal static string ViewMainList_NewEntry {
            get {
                return ResourceManager.GetString("ViewMainList_NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string ViewMainList_Notes {
            get {
                return ResourceManager.GetString("ViewMainList_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string ViewMainList_Params {
            get {
                return ResourceManager.GetString("ViewMainList_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ViewMainList_Search {
            get {
                return ResourceManager.GetString("ViewMainList_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ViewMainList_Tab_All_Title {
            get {
                return ResourceManager.GetString("ViewMainList_Tab_All_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ViewMainList_Title {
            get {
                return ResourceManager.GetString("ViewMainList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed characters: &apos;0&apos;..&apos;9&apos; &apos;A&apos;..&apos;F&apos;.
        /// </summary>
        internal static string ViewSetPW_AllowedChars {
            get {
                return ResourceManager.GetString("ViewSetPW_AllowedChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ViewSetPW_Cancel {
            get {
                return ResourceManager.GetString("ViewSetPW_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string ViewSetPW_NewPW {
            get {
                return ResourceManager.GetString("ViewSetPW_NewPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Control.
        /// </summary>
        internal static string ViewSetPW_NewPWControl {
            get {
                return ResourceManager.GetString("ViewSetPW_NewPWControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type it here again.
        /// </summary>
        internal static string ViewSetPW_NewPWControlHint {
            get {
                return ResourceManager.GetString("ViewSetPW_NewPWControlHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your password.
        /// </summary>
        internal static string ViewSetPW_NewPWHint {
            get {
                return ResourceManager.GetString("ViewSetPW_NewPWHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Password.
        /// </summary>
        internal static string ViewSetPW_Title {
            get {
                return ResourceManager.GetString("ViewSetPW_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Lock.
        /// </summary>
        internal static string ViewSettings_AutoLock {
            get {
                return ResourceManager.GetString("ViewSettings_AutoLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change App Password.
        /// </summary>
        internal static string ViewSettings_ChangePassword {
            get {
                return ResourceManager.GetString("ViewSettings_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Data before import.
        /// </summary>
        internal static string ViewSettings_ClearDb {
            get {
                return ResourceManager.GetString("ViewSettings_ClearDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt exported data.
        /// </summary>
        internal static string ViewSettings_EncryptedExport {
            get {
                return ResourceManager.GetString("ViewSettings_EncryptedExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default exported data are placed in the clipboard.
        /// </summary>
        internal static string ViewSettings_Explain {
            get {
                return ResourceManager.GetString("ViewSettings_Explain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        internal static string ViewSettings_ExportCsv {
            get {
                return ResourceManager.GetString("ViewSettings_ExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to SQL.
        /// </summary>
        internal static string ViewSettings_ExportSql {
            get {
                return ResourceManager.GetString("ViewSettings_ExportSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        internal static string ViewSettings_Go {
            get {
                return ResourceManager.GetString("ViewSettings_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CSV data.
        /// </summary>
        internal static string ViewSettings_ImportCsv {
            get {
                return ResourceManager.GetString("ViewSettings_ImportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App language.
        /// </summary>
        internal static string ViewSettings_Language {
            get {
                return ResourceManager.GetString("ViewSettings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock on hide.
        /// </summary>
        internal static string ViewSettings_LockOnHidde {
            get {
                return ResourceManager.GetString("ViewSettings_LockOnHidde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search everywhere.
        /// </summary>
        internal static string ViewSettings_SearchEverywhere {
            get {
                return ResourceManager.GetString("ViewSettings_SearchEverywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in notes.
        /// </summary>
        internal static string ViewSettings_SearchInNotes {
            get {
                return ResourceManager.GetString("ViewSettings_SearchInNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search options.
        /// </summary>
        internal static string ViewSettings_Section2 {
            get {
                return ResourceManager.GetString("ViewSettings_Section2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string ViewSettings_Section3 {
            get {
                return ResourceManager.GetString("ViewSettings_Section3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string ViewSettings_Section4 {
            get {
                return ResourceManager.GetString("ViewSettings_Section4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Export.
        /// </summary>
        internal static string ViewSettings_Section5 {
            get {
                return ResourceManager.GetString("ViewSettings_Section5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data import.
        /// </summary>
        internal static string ViewSettings_Section6 {
            get {
                return ResourceManager.GetString("ViewSettings_Section6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share data.
        /// </summary>
        internal static string ViewSettings_Share {
            get {
                return ResourceManager.GetString("ViewSettings_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle keys (login screen).
        /// </summary>
        internal static string ViewSettings_Shuffle {
            get {
                return ResourceManager.GetString("ViewSettings_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip existing ID&apos;s.
        /// </summary>
        internal static string ViewSettings_SkipId {
            get {
                return ResourceManager.GetString("ViewSettings_SkipId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip existing titles.
        /// </summary>
        internal static string ViewSettings_SkipTitles {
            get {
                return ResourceManager.GetString("ViewSettings_SkipTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ViewStteings_Title {
            get {
                return ResourceManager.GetString("ViewStteings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        internal static string VMDetail_CreatedOn {
            get {
                return ResourceManager.GetString("VMDetail_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified on.
        /// </summary>
        internal static string VMDetail_ModifiedOn {
            get {
                return ResourceManager.GetString("VMDetail_ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show date in grids.
        /// </summary>
        internal static string VSSettings_ShowDates {
            get {
                return ResourceManager.GetString("VSSettings_ShowDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lines in grids.
        /// </summary>
        internal static string VSSettings_ShowLines {
            get {
                return ResourceManager.GetString("VSSettings_ShowLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        internal static string VSSettings_Visual {
            get {
                return ResourceManager.GetString("VSSettings_Visual", resourceCulture);
            }
        }
    }
}
